# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Bundle Wishlists

on:
  push:
    branches: [ master, main ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
      token: ${{ secrets.BOT_PAT }}
    - name: Create wishlist bundles
      uses: actions/setup-node@v2
      with:
        node-version: 14.x
        cache: 'npm'
    - run: npm ci
    - run: npm run bundler
    
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: rebuilt bundles
        push_options: '--force'
